#!/bin/bash
# Device (e.g. Nothing Phone (1):sm7325-nothing-spacewar)
DEVICE="Nothing Phone (1):sm7325-nothing-spacewar"
ARCH="arm64"
# Partition for rootfs (linux or userdata is recommended)
PARTLABEL="userdata"

# Repositories and branches
declare -A REPOS=(
  ["KERNEL"]="https://github.com/mainlining/linux fekz115/spacewar"
  ["FIRMWARE"]="https://github.com/mainlining/firmware-nothing-spacewar master"
  ["ALSAUCM"]="https://github.com/mainlining/alsa-ucm-conf spacewar/pong"
)
DEFCONFIG="sm7325_defconfig nothing-spacewar.config"
CMDLINE="console=tty0 root=PARTLABEL=${PARTLABEL}"

# Maintainer
MAINTAINER="Alt Mobile <fix@me>"
